### PR TITLE
Avoiding conditional directives that break statements

### PR DESCRIPTION
**Pull request by RomeroMalaquias**
Hello, this change is only aesthetic, it's a suggestion to avoid the use of conditional directives that break statements i think that kind of concern improve the code maintainability do you agree?

### CODE REVIEW

**Comment by skinkie** [comment]
Hi, thank for the patch. The code you ar attempting to prettify is part of an upstream project http://www.pcre.org/ I would rather update the bundled version in Cherokee than to fork the code.

**Comment by RomeroMalaquias** [comment]
Ok, 
but do you see this kind of changes as an improvement?

**Comment by skinkie** [comment]
Sure, but I would love to see them on the core project. Maybe you are aware we have access to coverity analytics. Which can be a good starting point. An other interesting project might be to replace the existing pre-chula code in Cherokee with https://github.com/alobbs/libchula

**Comment by RomeroMalaquias** [comment]
Thanks for your time

**Pull request closed without merging**
