### PR TITLE
Fix two bugs in th issues

### PR DESCRIPTION
**Pull request by ycaibb**

### CODE REVIEW

**Comment by skinkie** [comment]
@ycaibb how did you find these?

**Comment by ycaibb** [comment]
By static code scan : )

**Comment by skinkie** [comment]
> By static code scan : )

And which tool did you use for this? Because a few years a go we used Coverity and these things did not pop up.

**Comment by ycaibb** [comment]
I wrote the tool, which hasn't been released.

**Comment by skinkie** [comment]
> I wrote the tool, which hasn't been released.

Obviously very curious :-) Can I request a test for another project? ;-)

**Comment by ycaibb** [comment]
Sure, I would love to! However, my tool only supports C/C++ and Java programs.

**Comment by CppXL** [comment]
> I wrote the tool, which hasn't been released.

Hi，I am a C/C++ testing beginner，Can I request it for learning test?

**Pull request merged**
